output_root: '/kaggle/working/output/'
data_dir: '/kaggle/input/'
experiment_name: "validation"
# res: 320
res: 224
batch_size: 16
num_workers: 4
run_crf: True
run_prediction: True
dark_mode: False
use_ddp: False

model_paths:
 - "/kaggle/input/potsdam-exp1-ckpt/potsdam_exp1.ckpt"

hydra:
  run:
    dir: "/kaggle/working/output/"
  output_subdir: "${hydra.run.dir}/${now:%Y-%m-%d_%H-%M-%S}"
